:open-collective: https://opencollective.com/home
= For Freelancers

What you can expect from link:/[Sepheo].

== Outline

From the link:/[front page]:

[quote]
--
include::_includes/pitch_to_freelancers.adoc[]
--

The basic idea works for all sorts of trades. We encourage diversity,
because in general all teams need a diverse range of skills. Saying
that, finding good matches depends on the mix of people and their
skills we have in our directory at any moment. This will change over
time - but you can find out more if you get in touch.

== How to connect with Sepheo

Here are several ways to connect.

=== 1. Talk to us

We're listening. See our link:/[front page] for ways of reaching us.

=== [[affiliation]]2. Register and become an Affiliate

Why?:: Perhaps you want to dip your toe in, open the door to
opportunities - but without committing to making contributions or
getting involved.

How?:: To do this, simply register on our directory. link:/affiliation/[More details here...]

What then?:: You get periodic status checks on your details and availability.
+
We may also contact about opportunities which arise, if your skills match.

=== [[membership]]3. Join as a Member

Why?:: You're freelancer: you'll want to find collaborators and
clients. You will also be helping us help *you* by supporting our
platform.  What this means...
+
- *You get put in touch* with other members in your area.
- *You can consult our matchmakers.* Through them you can access the
  directory of other members, leads, and organisations. They will help
  you to search for opportunities and collaborators.
- *You get consulted on major organisational decisions.* Sepheo is a
  members' association.
+
In the first instance, this means you can come to the online quarterly
  members calls. There we report back to our members, consult them,
  and elect the steward and matchmakers.
- *You fund the creation of more and/or better services* with a pledge
  to pay a minimum of £5/month. This an investment in Sepheo, a
  non-profit that exists for the benefits of its members,
  i.e. *you*.

How?:: Contribute as a "Member" on our Open Collective
page. link:/membership/[More details here...]

What then?:: We'll get in touch, invite you to join our members'
 Matrix chat, and give details of how to go from there.



== [[aspirations]]Future aspirations

Our plan is to growing our network organically, accumulating funds from
membership fees and matchmaking fees.

When the funds permit it, we then:

- Incorporate our organisation (although it will always remain a co-operative!)
- Pay stewards and matchmakers for their labour.

These will improve resilience and widen the options available to the
organisation. Stewards and matchmakers will be given greater security
and therefore the means to better serve the organisation.

If this works to plan, members get better support, more opportunities,
and newcomers more reasons to join. With better funding, the
organisation could become more ambitious with the services it
provides.

Some ideas of things this could lead to:

- Mutual support and special interest groups.
- Buyers' clubs to negotiate reduced prices.
- Mutual insurance, bread funds, etc.
- Training, mentoring and up-skilling.
- Tools and guidelines for team formation and governance.
- Support for incorporation of these teams as businesses in their own right.

In particular, we want to support *existing co-operatives*, create
*new co-operatives* and promote co-operative culture generally.

However, these are just examples - ultimately it depends on our
resources and what the membership asks for.

//  LocalWords:  Sepheo
