:open-collective: https://opencollective.com/home
= For Freelancers

What you can expect from link:/[Sepheo].

== Outline

From the link:/[front page]:

[quote]
--
include::_includes/pitch_to_freelancers.adoc[]
--

The basic idea works for all sorts of trades. We encourage diversity,
because in general all teams need a diverse range of skills. Saying
that, finding good matches depends on the mix of people and their
skills we have in our directory at any moment. This will change over
time - but you can find out more if you get in touch.

== How to connect with Sepheo

Here are several ways to connect.

=== 1. Talk to us

We're listening. See the links on our link:/[front page] for ways of reaching us.

=== [[affiliation]]2. Register and become an Affiliate

Why?:: If you just want to find out more, or perhaps you're looking
for opportunities but don't want to commit to paying the fee or being
involved too much with Sepheo, you can sign up as an *affiliate*.

How?:: To do this, simply register on our directory. link:/affiliation/[More details here...]

What then?:: You will then receive periodic status checks on your
availability and to ensure the directory details we have on you are up
to date.
+
We may also contact about opportunities which arise that need your
skills, and networking events in your area.

=== [[membership]]3. Join as a Member

Why?:: If you're freelancer and want to support Sepheo, meet other
members and have a say in the direction Sepheo takes, you can join as
a *member*.  What this means:
+
- You can consult our matchmakers. Through them you can access the
  directory of other members, leads, and organisations. They will help
  you to search for opportunities and collaborators. You will also be
  invited to get in touch with other members in your area.
- You get consulted on major organisational decisions, since Sepheo is
  a members association. In the first instance, this means you can
  come to the online quarterly members calls, at which we update
  members on the latest news, and hold the steward and matchmaker
  elections.
- You fund the creation of more and/or better services with a pledge
  to pay a minimum of £5/month. This an investment in Sepheo, a
  non-profit that exists for the benefits of its members,
  i.e. you. After administrative costs, any surplus funds are pooled
  to spend on more and/or better services for members later.

How?:: Contribute as a "Member" on our Open Collective
page. link:/membership/[More details here...]

What then?:: We'll get in touch, invite you to join our members'
 Matrix chat, and give details of how to go from there.



== [[aspirations]]Future aspirations

By growing our network organically, and accumulating funds from
membership fees and matchmaking fees, plan to:

- Incorporate our organisation (although it will always remain a co-operative!)
- Pay stewards and matchmakers for their labour.

Both of these will be needed to improve the resilience of the
organisation, which is otherwise dependent on pro-bono contributions
and puts stewards and matchmakers on the line as decision
makers. Voluntary workers who perform critical roles are notoriously
subject to burn-out!

The better-resourced stewards and matchmakers can then, should the
membership still wish it, try to raise more funding and build more
services, perhaps with more labour or capital requirements. Some
ideas:

- Mutual support and special interest groups.
- Buyers' clubs to negotiate reduced prices.
- Mutual insurance, bread funds, etc.
- Training, mentoring and up-skilling.
- Tools and guidelines for team formation and governance.
- Assistance with incorporation of these teams.

These are examples - ultimately it depends on our resources and what
the membership asks for.

//  LocalWords:  Sepheo
