// (See note about front-matter in op.adoc)
= We are Sepheo!

[.centre]
--
Sepheo is a mutual society for self-employed professionals.
--
== Sepheo what?

"Sepheo" stands for _"Self-Employed People Helping Each Other"_... that's the basic idea.

include::_includes/pitch_to_freelancers.adoc[]

== What we are not...

If you are a freelancer: :: We do not *supply your labour* to clients -
we support you, and introduce you to *client organisations* and *other
freelancers*.
+
You need to have the core skills - *we can't train you to do your
job*. But we do plan to *partner with people who provide training in a
range of areas*.

If you are an organisation: :: We do not deliver solutions or services
to you - we introduce you to *people who can*.
+
After the initial introduction, for which we accept a fee to cover our
costs, freelancers have *a direct relationship with their clients*.

== Contact Us

[#links]
--

Join our list of freelancers link:/register[here^].

OpenCollective: https://opencollective.com/sepheocoop#category-ABOUT[opencollective.com/sepheocoop^]

GitHub: https://github.com/sepheocoop[github.com/sepheocoop^]

E-mail: mailto:contact@sepheo.co[]

--
