// (See note about frontmatters in op.adoc)
= sepheo coop

SEPHEO (Self-Employed People Helping Each Other) Coop is a mutual society for self-employed professionals. We make it easy for freelancers to connect with coops and other aligned organisations.

As a coop, we subscribe to the https://en.wikipedia.org/wiki/Rochdale_Principles[Rochdale Co-operative principles], and the https://solidarityeconomyprinciples.org/[Solidarity Economy principles].

The problem: whilst employment in a typical company can be alienating (for reasons well understood to the co-op movement), co-ops are not a widely accessible alternative for most people. Their relative rarity, low visibility and unfamiliarity mean they're often not perceived as existing, yet alone as a possible alternative - even then they may be dismissed. In the other direction, co-ops often require a much higher degree of trust to grant membership than they would employment.

Freelancing is another way to attain more autonomy, and is becoming more common in the contemporary "gig economy", but can be precarious and isolating. It requires various legal, business, and social expertises outside the core skills of a professional - not to mention the confidence to attain these.

Our aim is to make co-operatives more visible and easier to access through the intermediate step of freelancing within co-operative contexts. Likewise, to make freelancers more visible and easier to access for co-operatives.

Sepheo connects co-operatives and freelancers by regularly checking-in with coops about their capacity needs and maintaining a list of freelancers that want to work with co-ops.

In the long term we want to act as a generative force in the coop economy, multiplying the efforts of others beyond what they thought possible.

[#links]
--

Join our list of freelancers link:/register[here^].

OpenCollective: https://opencollective.com/sepheocoop#category-ABOUT[opencollective.com/sepheocoop^]

GitHub: https://github.com/sepheocoop[github.com/sepheocoop^]

E-mail: mailto:contact@sepheo.co[]

--
