= How to join as a member

Why?:: You're freelancer who wants to find collaborators or clients
through our network, and help support the improvement of that network.
+
Members pledge to contribute £5/month. This your investment in Sepheo,
a co-operative mutual association. This means it is a democratically
governed organistion which works for the benefit of its members, i.e. you.
+
How this helps you:
+
- You can *find other members* in your area.
- You can *consult our matchmakers,* and through them access potential
  *leads* and *collaborators*.
- You *fund Sepheo to build more and/or better services*.
- You can *participate* in decisions on what those are.

How?:: Follow these steps:
+
. Start by *creating an account on link:{open-collective}[Open Collective^]*,
  if you don't have one. This is where we manage funds and pay
  expenses.
. *link:/affiliation/[Register]* - if you've not done that
  already.
. Then on our https://opencollective.com/sepheocoop[Open Collective^]
  page, *select the "Contribute" button on the "Member" option*.

What then?:: We'll get in touch, invite you to join our members'
 Matrix chat, and give details of how to go from there.
+
You should receive a confirmation of your subscription from Open
Collective.



