= For Organisations

What you can expect from link:/[Sepheo].

== Outline

When managing an organisation, typically you need to manage periods of
boom and bust with agility.

When opportunities arise you need more people. Conversely you may have
to shrink your workforce when work is scarce. And this has to be
balanced against commitment to your existing employees.

And perhaps you need specialised or short-term help.

These are examples of where temporary help can be essential.

Sepheo aims to facilitate your relationship building with freelancers.

== How we help you

- We maintain a directory of freelancers, their skills, and
  organisations who use them.
  - This is curated by our matchmakers - members of Sepheo who have
    been selected to make introductions.
- You can contact our matchmakers for help finding people with the
  right skills.
- If you register with us, our members can also contact our
  matchmakers to find you.
- If we find satisfactory matches for you whom you then hire, we ask
  for an introduction fee. (Currently this is negotiable whilst we
  tune the service, later will provide guidelines for the amount.)
- Your relationship with the freelancer is then your business - you
  hire directly, not through us.
- We are a non-profit, therefore this is likely cheaper than using a
  recruitment agency.
- We are accountable to our members - therefore we are likely to
  understand their skill-sets better.


If you are a co-operative or employee owned organisation, You may also like that:

- We support co-operative principles: democracy, self ownership,
  collaboration.
- Our members will understand co-operative organisations better than
  most - because they are part of one.

== What we are not

We are *not* an agency:

- You don't hire us, and we don't hire our members.
- We are not intermediates in the supply chain.
- After the initial introduction, your relationship to freelancers is direct.

== How to connect with Sepheo

If you're interested in Sepheo, you can simply get in touch using one
of the methods on the link:/[front page].

One of our matchmakers will then arrange a chat to find out what you
need, and give you the opportunity to register on our directory.

//  LocalWords:  Sepheo
