---
# Adapted from https://daiyi.co/blog/pr-previews-for-github-pages/

name: delete preview on PR close
on:
  pull_request:
    types: [closed]

jobs:
  erase_pr_preview:
    runs-on: ubuntu-24.04
    env:
      PATH_PREFIX: pull/${{github.event.number}}/
    steps:
      - name: make empty dir
        run: mkdir empty

      - name: empty PR folder ${{ env.PATH_PREFIX }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./empty
          target-folder: ${{ env.PATH_PREFIX }}

      - name: Comment on PR
        uses: hasura/comment-progress@v2.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.number }}
          id: deploy-preview
          message: |
            🪓 PR closed, deleted preview at https://github.com/${{ github.repository }}/tree/gh-pages/${{ env.PATH_PREFIX }}
